### ISSUE TITLE
Не обновляется чат

### ISSUE THREAD

**Issue by vpArth** [kakserpom/phpdaemon-muchat#3]
Не знаю, это проблема на сайте или в коде чата
http://daemon.io/examples.html - новые сообщения в чате появляются только после обновления страницы(F5)

в логах вижу только запросы списка пользователей:
`{"cmd":"getUserlist","tags":["phpdaemon"]}`

`User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36`

**Comment by kakserpom** [comment]
Проблема вероятно в том что вы не выполнили createCollection с флагом capped = true.

**Comment by vpArth** [comment]
Хм, Вы - это кто?  Я думал - это Ваш сайт)

**Comment by kakserpom** [comment]
А, я думал вы запустили этот пример у себя :)

**Comment by vpArth** [comment]
Assume it's abandoned
